/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Lucas
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        pnlLivro = new javax.swing.JPanel();
        dadoTituloLivro = new javax.swing.JLabel();
        pnlLinhaLivros = new javax.swing.JPanel();
        dadoNomeLivro = new javax.swing.JLabel();
        dadoAutor = new javax.swing.JLabel();
        dadoGenero = new javax.swing.JLabel();
        dadoQtd = new javax.swing.JLabel();
        pnlMembros = new javax.swing.JPanel();
        dadoTituloMembro = new javax.swing.JLabel();
        pnlLinhaMembro = new javax.swing.JPanel();
        dadoID = new javax.swing.JLabel();
        dadoNome = new javax.swing.JLabel();
        dadoEmail = new javax.swing.JLabel();
        dadoUsuario = new javax.swing.JLabel();
        pnlDevolucao = new javax.swing.JPanel();
        dadoTitulo = new javax.swing.JLabel();
        dadoLivro = new javax.swing.JLabel();
        txtLivro = new javax.swing.JTextField();
        dadoMembro = new javax.swing.JLabel();
        txtMembro = new javax.swing.JTextField();
        dadoDevolucao = new javax.swing.JLabel();
        txtDevolucao = new javax.swing.JTextField();
        btnDevolucao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(0, 107, 0));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(254, 254, 254));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-return.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.setBorderPainted(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        pnlLivro.setBackground(new java.awt.Color(0, 0, 157));
        pnlLivro.setPreferredSize(new java.awt.Dimension(294, 712));
        pnlLivro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dadoTituloLivro.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        dadoTituloLivro.setForeground(new java.awt.Color(255, 255, 255));
        dadoTituloLivro.setText("Detalhes do Livro");
        pnlLivro.add(dadoTituloLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        pnlLinhaLivros.setBackground(new java.awt.Color(255, 255, 255));
        pnlLinhaLivros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlLivro.add(pnlLinhaLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 116, 290, 10));

        dadoNomeLivro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoNomeLivro.setForeground(new java.awt.Color(255, 255, 255));
        dadoNomeLivro.setText("Nome do Livro: ");
        pnlLivro.add(dadoNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 253, -1, -1));

        dadoAutor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoAutor.setForeground(new java.awt.Color(255, 255, 255));
        dadoAutor.setText("Autor:");
        pnlLivro.add(dadoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 303, -1, -1));

        dadoGenero.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoGenero.setForeground(new java.awt.Color(255, 255, 255));
        dadoGenero.setText("Gênero:");
        pnlLivro.add(dadoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 353, -1, -1));

        dadoQtd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoQtd.setForeground(new java.awt.Color(255, 255, 255));
        dadoQtd.setText("Quantidade:");
        pnlLivro.add(dadoQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 403, -1, -1));

        getContentPane().add(pnlLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 294, 712));

        pnlMembros.setBackground(new java.awt.Color(0, 107, 0));
        pnlMembros.setPreferredSize(new java.awt.Dimension(294, 712));
        pnlMembros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dadoTituloMembro.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        dadoTituloMembro.setForeground(new java.awt.Color(255, 255, 255));
        dadoTituloMembro.setText("Detalhes do Membro");
        pnlMembros.add(dadoTituloMembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pnlLinhaMembro.setBackground(new java.awt.Color(255, 255, 255));
        pnlLinhaMembro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMembros.add(pnlLinhaMembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 116, 290, 10));

        dadoID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoID.setForeground(new java.awt.Color(255, 255, 255));
        dadoID.setText("ID:");
        pnlMembros.add(dadoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 253, -1, -1));

        dadoNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoNome.setForeground(new java.awt.Color(255, 255, 255));
        dadoNome.setText("Nome:");
        pnlMembros.add(dadoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 303, -1, -1));

        dadoEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoEmail.setForeground(new java.awt.Color(255, 255, 255));
        dadoEmail.setText("Email:");
        pnlMembros.add(dadoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 353, -1, -1));

        dadoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dadoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        dadoUsuario.setText("Usuário:");
        pnlMembros.add(dadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 403, -1, -1));

        getContentPane().add(pnlMembros, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 0, 294, 712));

        pnlDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        pnlDevolucao.setPreferredSize(new java.awt.Dimension(294, 712));
        pnlDevolucao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dadoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dadoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        dadoTitulo.setText("Devolução Livros");
        pnlDevolucao.add(dadoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 50));

        dadoLivro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dadoLivro.setText("Nome do livro");
        pnlDevolucao.add(dadoLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        txtLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLivro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLivroActionPerformed(evt);
            }
        });
        pnlDevolucao.add(txtLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 30));

        dadoMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dadoMembro.setText("ID do membro");
        pnlDevolucao.add(dadoMembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        txtMembro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMembro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMembro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMembroActionPerformed(evt);
            }
        });
        pnlDevolucao.add(txtMembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 30));

        dadoDevolucao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dadoDevolucao.setText("Data da devolução");
        pnlDevolucao.add(dadoDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, -1));

        txtDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevolucaoActionPerformed(evt);
            }
        });
        pnlDevolucao.add(txtDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 30));

        btnDevolucao.setBackground(new java.awt.Color(0, 102, 0));
        btnDevolucao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDevolucao.setForeground(new java.awt.Color(254, 254, 254));
        btnDevolucao.setText("Realizar devolução");
        btnDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDevolucao.setBorderPainted(false);
        btnDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucaoActionPerformed(evt);
            }
        });
        pnlDevolucao.add(btnDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 40));

        getContentPane().add(pnlDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 0, 294, 712));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLivroActionPerformed

    private void txtMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMembroActionPerformed

    private void btnDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolucaoActionPerformed

    private void txtDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevolucaoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel dadoAutor;
    private javax.swing.JLabel dadoDevolucao;
    private javax.swing.JLabel dadoEmail;
    private javax.swing.JLabel dadoGenero;
    private javax.swing.JLabel dadoID;
    private javax.swing.JLabel dadoLivro;
    private javax.swing.JLabel dadoMembro;
    private javax.swing.JLabel dadoNome;
    private javax.swing.JLabel dadoNomeLivro;
    private javax.swing.JLabel dadoQtd;
    private javax.swing.JLabel dadoTitulo;
    private javax.swing.JLabel dadoTituloLivro;
    private javax.swing.JLabel dadoTituloMembro;
    private javax.swing.JLabel dadoUsuario;
    private javax.swing.JPanel pnlDevolucao;
    private javax.swing.JPanel pnlLinhaLivros;
    private javax.swing.JPanel pnlLinhaMembro;
    private javax.swing.JPanel pnlLivro;
    private javax.swing.JPanel pnlMembros;
    private javax.swing.JTextField txtDevolucao;
    private javax.swing.JTextField txtLivro;
    private javax.swing.JTextField txtMembro;
    // End of variables declaration//GEN-END:variables
}
