/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Marcelo
 */
public class TeacherPage extends javax.swing.JFrame {

    /**
     * Creates new form TelaTeacher
     */
    public TeacherPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTeacher = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Books = new javax.swing.JLabel();
        txtBooks = new javax.swing.JTextField();
        Papers = new javax.swing.JLabel();
        txtPapers = new javax.swing.JTextField();
        Teacher = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Professor");
        setSize(new java.awt.Dimension(882, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTeacher.setBackground(new java.awt.Color(254, 254, 254));
        pnlTeacher.setAlignmentX(0.0F);
        pnlTeacher.setAlignmentY(0.0F);
        pnlTeacher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(19, 62, 121));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-return.png"))); // NOI18N
        btnBack.setText("Voltar");
        btnBack.setToolTipText("Voltar");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlTeacher.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 39));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(19, 62, 121));
        Name.setText("Nome:");
        pnlTeacher.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, 30));

        txtName.setToolTipText("Digite seu nome");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlTeacher.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, -1));

        txtEmail.setToolTipText("Digite seu email");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlTeacher.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, -1));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(19, 62, 121));
        Password.setText("Autor:");
        pnlTeacher.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, 30));

        Books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Books.setForeground(new java.awt.Color(19, 62, 121));
        Books.setText("Gênero:");
        pnlTeacher.add(Books, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 30));

        txtBooks.setToolTipText("Digite seu nome");
        txtBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBooksActionPerformed(evt);
            }
        });
        pnlTeacher.add(txtBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 200, -1));

        Papers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Papers.setForeground(new java.awt.Color(19, 62, 121));
        Papers.setText("Artigos:");
        pnlTeacher.add(Papers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 200, 30));

        txtPapers.setToolTipText("Digite seu nome");
        txtPapers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPapersActionPerformed(evt);
            }
        });
        pnlTeacher.add(txtPapers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 200, -1));

        Teacher.setBackground(new java.awt.Color(255, 255, 255));
        Teacher.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Teacher.setForeground(new java.awt.Color(0, 102, 0));
        Teacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Teacher.setText("Submissão de Papers");
        pnlTeacher.add(Teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 6, 468, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 62, 121));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UnB Lib");
        pnlTeacher.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-icon-teacher.png"))); // NOI18N
        pnlTeacher.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 360, 270));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unb-icon.png"))); // NOI18N
        pnlTeacher.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 280, 110));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Solicitar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pnlTeacher.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, 360));

        getContentPane().add(pnlTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jPanel1.setBackground(new java.awt.Color(19, 62, 121));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 160, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBooksActionPerformed

    private void txtPapersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPapersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPapersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Books;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Papers;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Teacher;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlTeacher;
    private javax.swing.JTextField txtBooks;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPapers;
    // End of variables declaration//GEN-END:variables
}
